@startuml
!pragma layout smetana
skin rose

package cl.ucn.disc.pa.kanto {

   package in {

        package reader {

            interface PokemonReader {
            }

        }

        package write {

            interface PokemonWriter {
            }
        }

   }

    package pokedex {

        interface Pokedex {

        }

        interface PokedexLoader {
        }

    }

    package pokemon {

        class Pokemon {

            id : String
            name : String
            stage : String
            previousEvolution : String
            nextEvolution : String
            kindOne : String
            kindTwo : String

            + Pokemon(id : String, name : String, stage : String, previousEvolution : String,
            nextEvolution : String, kindOne : String, kindTwo : String)

            + getId() : String
            + getName() : String
            + getStage() : String
            + getPreviousEvolution() : String
            + getNextEvolution() : String
            + getKindOne() : String
            + getKindTwo() : String




        }

        interface Showable {
        }

    }

    Pokemon ..|> Showable

}

@enduml